# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            artinpocket/regular
tagline:          Un projecte d'artinpocket
description:      Bloc del <a href="http://www.verkami.com/" target="_blank">Verkami</a> <a href="http://www.artinpocket.cat" target="_blank">artinpocket</a> per dur una nova tipografia a l'art. Creat per <a href="http://www.oxygen.cat/" target="_blank">Oxygen.cat</a>.
url:              http://www.artinpocketregular.com

author:
  name:           'Ramon Gil'
  url:            https://twitter.com/freecates

paginate:         5

# Custom vars
version:          1.0.0

verkami:
  repo:           http://www.verkami.com/
